FROM hadolint/hadolint:v2.12.0 AS hadolint

FROM python:3.12-slim

WORKDIR /app

COPY --from=hadolint /bin/hadolint /usr/local/bin/hadolint

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc && \
    rm -rf /var/lib/apt/lists/*

COPY "requirements.txt" .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r "requirements.txt"

COPY . .

EXPOSE 8000

CMD ["fastapi", "run", "--host", "0.0.0.0"]
