services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dockerforge}
      POSTGRES_USER: ${POSTGRES_USER:-dockerforge}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dockerforge}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
