"""add build_package and base_image to projects

Revision ID: 35bfbb5d4ad4
Revises: d266e6ac5afd
Create Date: 2026-04-05 01:21:39.552858

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35bfbb5d4ad4"
down_revision: Union[str, None] = "d266e6ac5afd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("build_package", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("base_image", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "base_image")
    op.drop_column("projects", "build_package")
    # ### end Alembic commands ###
