"""add total_builds and last_build_at to projects

Revision ID: 462cbdfcf9dd
Revises: e606fec21678
Create Date: 2026-04-19 11:55:41.492373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462cbdfcf9dd'
down_revision: Union[str, None] = 'e606fec21678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total_builds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('projects', sa.Column('last_build_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_build_at')
    op.drop_column('projects', 'total_builds')
    # ### end Alembic commands ###
