"""add is_frontend to projects

Revision ID: 6a546a08abac
Revises: 38bb24c54abe
Create Date: 2026-03-29 17:52:44.177547

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a546a08abac"
down_revision: Union[str, None] = "38bb24c54abe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "is_frontend", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_frontend")
    # ### end Alembic commands ###
