"""add rust to language enum

Revision ID: 9704080220fb
Revises: 6a546a08abac
Create Date: 2026-04-04 22:34:34.015729

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9704080220fb"
down_revision: Union[str, None] = "6a546a08abac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE languageenum ADD VALUE IF NOT EXISTS 'rust'")
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError(
        "Cannot remove 'rust' from languageenum automatically. "
        "Postgres requires recreating the enum type and re-casting every column "
        "that uses it, plus deciding what to do with rows currently set to 'rust'. "
        "If you truly need to revert, do it manually."
    )
