"""add image_cleaned_at to builds

Revision ID: 98d1a40eea0f
Revises: 462cbdfcf9dd
Create Date: 2026-04-25 12:53:33.051536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d1a40eea0f'
down_revision: Union[str, None] = '462cbdfcf9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('image_cleaned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('builds', 'image_cleaned_at')
    # ### end Alembic commands ###
