"""add dockerignore_content to builds

Revision ID: 9b68cbc587ba
Revises: 35bfbb5d4ad4
Create Date: 2026-04-05 14:23:26.761461

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b68cbc587ba"
down_revision: Union[str, None] = "35bfbb5d4ad4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("builds", sa.Column("dockerignore_content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("builds", "dockerignore_content")
    # ### end Alembic commands ###
