"""replace is_frontend with framework and add entry_point binary_name build_output_dir

Revision ID: d266e6ac5afd
Revises: 9704080220fb
Create Date: 2026-04-04 23:37:48.649469

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d266e6ac5afd"
down_revision: Union[str, None] = "9704080220fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("framework", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("entry_point", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("binary_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "projects", sa.Column("build_output_dir", sa.String(length=255), nullable=True)
    )
    op.drop_column("projects", "is_frontend")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "is_frontend",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("projects", "build_output_dir")
    op.drop_column("projects", "binary_name")
    op.drop_column("projects", "entry_point")
    op.drop_column("projects", "framework")
    # ### end Alembic commands ###
